spring:
  application:
    name: BankApp
  datasource:
    url: jdbc:postgresql://localhost:5432/BankApp
    username: postgres
    password: Gunnersfan.33
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    clear-check-sums: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
    packages-to-scan: your.package.driving.rest
  openapi:
    info:
      title: BankApp API
      version: 1.0.0
      description: Documentation des APIs pour la gestion des clients et comptes bancaires.
